---
title: "Sexual Offenses and Alcohol Abuse at Pennsylvania State University Campuses"
author: "Sarah Kircher, Leigh Stern, and Nathanael Kovscek"
date: "`r Sys.Date()`"
output: html_notebook
---

# Introduction

Insert introduction here.

```{r setUp}
# Load needed packages
library(ggplot2)
library(readxl)

```


```{r loadData}
# Load dataset 1 from Excel - PSU student alcohol consumptions
alcohol_consumption <- read_excel("PSU_students_report_consuming_alc.xlsx")

# Load dataset 2 from Excel - PSU student high risk drinking by sex
hr_drinking_sex <- read_excel("PSU_high_risk_drinking_sex.xlsx")

# Load dataset 3 from Excel - PSU student drinking consequences
drinking_consequences <- read_excel("PSU_drinking_consequences.xlsx")
```


# First Question
```{r alcoholConsumption}
# Create ggplot2 for PSU student alcohol consumption over time
# One line/trend for respondents who do drink
# One line/trend for respondents who do not drink
alc_consump_colors <- c("Drinker" = "red", "Non-Drinker" = "gray")

alc_consump <- ggplot(
  data = alcohol_consumption, 
  aes(x = year)
) + 
  geom_point(aes(y = drink_num, color = "Drinker"), size = 2.25) +
  geom_point(aes(y = not_drink_num, color = "Non-Drinker"), size = 2.25) +
  
  geom_line(aes(y = drink_num, color = "Drinker"), size = 1) + 
  geom_line(aes(y = not_drink_num, color = "Non-Drinker"), size = 1) +
  labs(x = "Year", y = "Respondents", color = "Drinker Status") +
  ggtitle("Penn State Student Alcohol Consumption Over Time") +
  scale_color_manual(values = alc_consump_colors) +
  theme_minimal()

```


Insert data source information, visualization, and write-up here.

# Second Question

Insert data source information, visualization, and write-up here.

# Third Question

Insert data source information, visualization, and write-up here.




